# Generated by Django 4.2.10 on 2025-05-17 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("to_emails", models.TextField()),
                ("cc_emails", models.TextField(blank=True)),
                ("bcc_emails", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("html_body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-created_at"],
            },
        ),
    ]
